// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllowClose():Promise<void>;

export function GetStoredHash():Promise<string>;

export function LoadConstants():Promise<Record<string, any>>;

export function LoadJSONFile():Promise<string>;

export function LoadMaterialInventory():Promise<Record<string, any>>;

export function SaveConstants(arg1:any):Promise<string>;

export function SaveFile(arg1:string):Promise<string>;

export function SaveMaterialInventory(arg1:any):Promise<string>;
