// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadConstants():Promise<Record<string, any>>;

export function LoadJSONFile():Promise<string>;

export function SaveConstants(arg1:any):Promise<string>;

export function SaveFile(arg1:string):Promise<string>;
